---
fs_pgp_pubkeys: '../pgp_pubkeys'
dropbox_view_url_format: 'http://localhost:6543/briefkasten/dropbox/%s'
dropbox_editor_url_format: 'http://localhost:6543/briefkasten/dropbox/%s/%s'
test_submission_secret: changeme
debug: True
editors:
  - tom@tomster.org
  - erdgeist@erdgeist.org
admins:
 - tom@tomster.org
 - erdgeist@erdgeist.org
mail.host: localhost
mail.port: 8025
mail.default_sender: noreply@briefkasten
attachment_size_threshold: 2Mb
