---
- name: make sure poudriere is installed
  pkgng:
    name: "{{item}}"
    state: present
  with_items:
    - poudriere
    - rsync
  tags: poudriere

- name: poudriere configuration
  template:
    src: poudriere.conf.j2
    dest: /usr/local/etc/poudriere.conf
  tags: 
    - poudriere
    - poudriere-conf

- name: create ports tree directories
  command: poudriere ports -c -p briefkasten creates=/usr/local/poudriere/ports/briefkasten
  tags: poudriere

- name: create build jail
  command: poudriere jail -c -j 102amd64 -v 10.2-RELEASE -a amd64 creates=/usr/local/poudriere/jails/102amd64
  tags: poudriere

- name: configure build jail
  copy:
    src: 102amd64-make.conf
    dest: /usr/local/etc/poudriere.d/102amd64-make.conf
  tags: poudriere

- name: upload package options
  copy:
    src: 102amd64-briefkasten-options/
    dest: /usr/local/etc/poudriere.d/102amd64-briefkasten-options/
    directory_mode: yes
  tags:
    - poudriere

- name: upload package list
  copy:
    src: pkg_list
    dest: /usr/local/etc/poudriere.d/briefkasten-pkglist
  tags: poudriere

- name: create distfiles cache directory
  file:
    path: "{{ distfiles_cache }}"
    state: directory
  tags: poudriere


