[project]
name = "briefkasten-deployment"
version = "0.4.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "ansible<5",
    "bsdploy",
    "keyring",
    "ploy",
    "ploy-ec2",
]

[tool.uv.sources]
bsdploy = { git = "https://github.com/witsch/bsdploy.git", rev = "4029c5fa1059d9cf932fdf1366ed663c088bf659" }
