---
- name: restart ezjail
  service: name=ezjail state=restarted
- name: restart sshd
  service: name=sshd state=restarted
- name: restart pf
  service: name=pf state=restarted
- name: restart supervisord
  service: name=supervisord state=restarted
